# Phase 0: Prerequisites (Foundations)

## 🎯 Learning Objectives
By the end of this phase, you will:
- ✅ Write Python code for data manipulation
- ✅ Use NumPy for numerical operations
- ✅ Handle datasets with Pandas
- ✅ Visualize data with Matplotlib and Seaborn
- ✅ Load and prepare data for ML

**Time Required:** 1-2 weeks  
**Difficulty:** Beginner

---
## 0.1 Python Essentials for ML

### Variables and Data Types

In [ ]:
# Basic variables
name = "Machine Learning"
age = 25
height = 5.9
is_student = True

# Lists (ordered, mutable)
scores = [85, 90, 78, 92, 88]
print(f"First score: {scores[0]}")

# Dictionaries (key-value pairs)
student = {
    "name": "John",
    "age": 22,
    "grades": [85, 90, 88]
}
print(f"Student name: {student['name']}")

### Loops and Conditionals

In [ ]:
# For loop
numbers = [1, 2, 3, 4, 5]
for num in numbers:
    print(f"{num} * 2 = {num * 2}")

In [ ]:
# While loop
count = 0
while count < 5:
    print(f"Count is: {count}")
    count += 1

In [ ]:
# If-else
score = 85
if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
else:
    grade = "C"
print(f"Grade: {grade}")

### Functions

In [1]:
# Simple function
def calculate_average(numbers):
    """Calculate average of a list of numbers"""
    total = sum(numbers)
    count = len(numbers)
    return total / count

scores = [85, 90, 78, 92, 88]
avg = calculate_average(scores)
print(f"Average: {avg}")

Average: 86.6


In [ ]:
# Function with multiple parameters
def greet(name, age=25):
    """Greet a person with their name and age"""
    return f"Hello {name}, you are {age} years old"

print(greet("Alice"))
print(greet("Bob", 30))

### List Comprehensions (ML Essential!)

In [2]:
# Traditional way
squares = []
for x in range(10):
    squares.append(x ** 2)
print("Traditional:", squares)

# List comprehension way (preferred in ML)
squares = [x ** 2 for x in range(10)]
print("List comprehension:", squares)

# With condition
even_squares = [x ** 2 for x in range(10) if x % 2 == 0]
print("Even squares:", even_squares)

Traditional: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
List comprehension: [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Even squares: [0, 4, 16, 36, 64]


---
## 0.2 Essential Libraries

### 📦 NumPy - Numerical Python

NumPy is the foundation of ML in Python. It provides fast array operations.

In [3]:
import numpy as np

# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

print("1D Array:", arr1)
print("Shape:", arr1.shape)
print("\n2D Array:")
print(arr2)
print("Shape:", arr2.shape)

1D Array: [1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [4]:
# Array creation functions
zeros = np.zeros((3, 4))        # 3x4 array of zeros
ones = np.ones((2, 3))          # 2x3 array of ones
random = np.random.rand(3, 3)   # 3x3 array of random values (0-1)
range_arr = np.arange(0, 10, 2) # Array from 0 to 10, step 2
linspace = np.linspace(0, 1, 5) # 5 values from 0 to 1

print("Zeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nRandom:\n", random)
print("\nRange:", range_arr)
print("Linspace:", linspace)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Random:
 [[0.80218864 0.39157365 0.8653819 ]
 [0.48485094 0.86944877 0.84521887]
 [0.68932258 0.06008758 0.94040214]]

Range: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


#### Array Operations (Vectorization)

In [5]:
# Element-wise operations (FAST!)
arr = np.array([1, 2, 3, 4, 5])

# Operations on entire array
print("Original:", arr)
print("Add 10:", arr + 10)
print("Multiply by 2:", arr * 2)
print("Square:", arr ** 2)

# Mathematical functions
print("\nSquare root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Natural log:", np.log(arr))

Original: [1 2 3 4 5]
Add 10: [11 12 13 14 15]
Multiply by 2: [ 2  4  6  8 10]
Square: [ 1  4  9 16 25]

Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [6]:
# Array operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)

# Statistical operations
data = np.array([10, 20, 30, 40, 50])
print(f"\nData: {data}")
print(f"Mean: {np.mean(data)}")
print(f"Median: {np.median(data)}")
print(f"Std Dev: {np.std(data):.2f}")
print(f"Min: {np.min(data)}")
print(f"Max: {np.max(data)}")

Array 1: [1 2 3]
Array 2: [4 5 6]
Addition: [5 7 9]
Multiplication: [ 4 10 18]

Data: [10 20 30 40 50]
Mean: 30.0
Median: 30.0
Std Dev: 14.14
Min: 10
Max: 50


#### Array Indexing and Slicing

In [13]:
arr = np.array([10, 20, 30, 40, 50,60,70])

# Indexing
print("Array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing [start:end:step]
print("\nSlicing:")
print("arr[1:4]:", arr[1:4])
print("arr[:3]:", arr[:3])
print("arr[::2]:", arr[::2])

Array: [10 20 30 40 50 60 70]
First element: 10
Last element: 70

Slicing:
arr[1:4]: [20 30 40]
arr[:3]: [10 20 30]
arr[::2]: [10 30 50 70]


In [ ]:
# Boolean indexing (ML ESSENTIAL!)
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3

print("Array:", arr)
print("Mask (arr > 3):", mask)
print("Values > 3:", arr[mask])

# One line
print("Direct filtering:", arr[arr > 3])

#### 2D Array Operations

In [16]:
# Creating 2D array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:")
print(matrix)
print(f"Shape: {matrix.shape}")

# Indexing 2D arrays
print(f"\nElement [0, 0]: {matrix[0, 0]}")
print(f"Element [1, 2]: {matrix[1, 2]}")
print(f"First row: {matrix[0]}")
print(f"First column: {matrix[:, 0]}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

Element [0, 0]: 1
Element [1, 2]: 6
First row: [1 2 3]
First column: [1 4 7]


In [17]:
# Matrix operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nA + B (element-wise):")
print(A + B)
print("\nA * B (element-wise):")
print(A * B)
print("\nA @ B (matrix multiplication):")
print(A @ B)
print("\nTranspose of A:")
print(A.T)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A + B (element-wise):
[[ 6  8]
 [10 12]]

A * B (element-wise):
[[ 5 12]
 [21 32]]

A @ B (matrix multiplication):
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]


---
### 📊 Pandas - Data Analysis

In [ ]:
import pandas as pd

# Creating DataFrames from dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'Salary': [50000, 60000, 75000, 55000],
    'Department': ['HR', 'IT', 'IT', 'Sales']
}
df = pd.DataFrame(data)
print(df)

#### Basic DataFrame Operations

In [ ]:
# Create more comprehensive dataset
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 28, 32],
    'Salary': [50000, 60000, 75000, 55000, 65000],
    'Department': ['HR', 'IT', 'IT', 'Sales', 'HR']
})

# Basic info
print("First 3 rows:")
print(df.head(3))
print(f"\nShape: {df.shape}")
print(f"\nColumns: {df.columns.tolist()}")
print(f"\nData types:\n{df.dtypes}")

In [ ]:
# Statistical summary
print("Statistical Summary:")
print(df.describe())

In [ ]:
# Selecting columns
print("Single column (Series):")
print(df['Name'])
print(f"\nType: {type(df['Name'])}")

print("\nMultiple columns (DataFrame):")
print(df[['Name', 'Age']])
print(f"Type: {type(df[['Name', 'Age']])}")

In [ ]:
# Selecting rows
print("Row by label (loc):")
print(df.loc[0])

print("\nRow by position (iloc):")
print(df.iloc[0])

print("\nConditional selection (Age > 30):")
print(df[df['Age'] > 30])

In [ ]:
# Adding new column
df['Bonus'] = df['Salary'] * 0.1
print("DataFrame with Bonus column:")
print(df)

#### Data Filtering and Sorting

In [ ]:
# Create sample data
df = pd.DataFrame({
    'Product': ['A', 'B', 'C', 'D', 'E'],
    'Price': [100, 150, 200, 120, 180],
    'Quantity': [10, 5, 8, 15, 7],
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics']
})

print("Original Data:")
print(df)

In [ ]:
# Filtering
print("Products with Price > 150:")
high_price = df[df['Price'] > 150]
print(high_price)

In [ ]:
# Multiple conditions
print("Electronics with Price > 150:")
electronics_high_price = df[(df['Category'] == 'Electronics') & (df['Price'] > 150)]
print(electronics_high_price)

In [ ]:
# Sorting
print("Sorted by Price (descending):")
sorted_df = df.sort_values('Price', ascending=False)
print(sorted_df)

In [ ]:
# Groupby (VERY IMPORTANT!)
print("Average Price by Category:")
category_avg = df.groupby('Category')['Price'].mean()
print(category_avg)

#### Handling Missing Data

In [ ]:
# Data with missing values
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, 8, 9],
    'C': [10, 11, 12, 13, 14]
})

print("Data with missing values:")
print(df)

print("\nMissing values (True/False):")
print(df.isnull())

print("\nCount of missing values per column:")
print(df.isnull().sum())

In [ ]:
# Drop missing values
print("Drop rows with any NaN:")
df_dropped = df.dropna()
print(df_dropped)

In [ ]:
# Fill missing values
print("Fill with 0:")
df_filled = df.fillna(0)
print(df_filled)

print("\nFill with column mean:")
df_filled_mean = df.fillna(df.mean())
print(df_filled_mean)

---
### 📈 Matplotlib - Data Visualization

In [ ]:
import matplotlib.pyplot as plt

# Line plot
x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.figure(figsize=(10, 6))
plt.plot(x, y, label='sin(x)', color='blue', linewidth=2)
plt.xlabel('X axis')
plt.ylabel('Y axis')
plt.title('Sine Wave')
plt.legend()
plt.grid(True)
plt.show()

In [ ]:
# Scatter plot
x = np.random.rand(50)
y = np.random.rand(50)
colors = np.random.rand(50)
sizes = 1000 * np.random.rand(50)

plt.figure(figsize=(8, 6))
plt.scatter(x, y, c=colors, s=sizes, alpha=0.5, cmap='viridis')
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Scatter Plot')
plt.colorbar()
plt.show()

In [ ]:
# Bar plot
categories = ['A', 'B', 'C', 'D', 'E']
values = [23, 45, 56, 78, 32]

plt.figure(figsize=(8, 6))
plt.bar(categories, values, color='skyblue', edgecolor='black')
plt.xlabel('Categories')
plt.ylabel('Values')
plt.title('Bar Chart')
plt.show()

In [ ]:
# Histogram
data = np.random.randn(1000)

plt.figure(figsize=(8, 6))
plt.hist(data, bins=30, color='green', alpha=0.7, edgecolor='black')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.title('Histogram')
plt.show()

#### Multiple Subplots

In [ ]:
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

# Plot 1: Line
x = np.linspace(0, 10, 100)
axes[0, 0].plot(x, np.sin(x))
axes[0, 0].set_title('Sine Wave')

# Plot 2: Scatter
axes[0, 1].scatter(np.random.rand(50), np.random.rand(50))
axes[0, 1].set_title('Scatter Plot')

# Plot 3: Bar
axes[1, 0].bar(['A', 'B', 'C'], [1, 2, 3])
axes[1, 0].set_title('Bar Chart')

# Plot 4: Histogram
axes[1, 1].hist(np.random.randn(1000), bins=30)
axes[1, 1].set_title('Histogram')

plt.tight_layout()
plt.show()

---
### 🎨 Seaborn - Statistical Visualization

In [ ]:
import seaborn as sns

# Set style
sns.set_style('whitegrid')

# Sample data
df = pd.DataFrame({
    'Age': np.random.randint(20, 60, 100),
    'Salary': np.random.randint(30000, 100000, 100),
    'Department': np.random.choice(['IT', 'HR', 'Sales', 'Marketing'], 100)
})

print("Sample data:")
print(df.head())

In [ ]:
# Distribution plot
plt.figure(figsize=(10, 6))
sns.histplot(df['Age'], kde=True, bins=20)
plt.title('Age Distribution')
plt.show()

In [ ]:
# Scatter plot with regression line
plt.figure(figsize=(10, 6))
sns.regplot(x='Age', y='Salary', data=df)
plt.title('Age vs Salary')
plt.show()

In [ ]:
# Box plot
plt.figure(figsize=(10, 6))
sns.boxplot(x='Department', y='Salary', data=df)
plt.title('Salary by Department')
plt.show()

In [ ]:
# Correlation heatmap
numeric_df = df[['Age', 'Salary']]
correlation = numeric_df.corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation, annot=True, cmap='coolwarm', center=0)
plt.title('Correlation Matrix')
plt.show()

In [ ]:
# Pairplot (VERY USEFUL for ML!)
sns.pairplot(df, hue='Department')
plt.show()

---
### 🤖 Scikit-learn - ML Library (Preview)

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Labels

# Convert to DataFrame for better visualization
df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = y

print("Iris Dataset:")
print(df.head())
print(f"\nDataset shape: {X.shape}")
print(f"Number of classes: {len(set(y))}")

In [ ]:
# Split data (we'll use this A LOT)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Training set size: {X_train.shape}")
print(f"Test set size: {X_test.shape}")

In [ ]:
# Feature scaling (normalization)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Original data range: {X_train[:, 0].min():.2f} to {X_train[:, 0].max():.2f}")
print(f"Scaled data range: {X_train_scaled[:, 0].min():.2f} to {X_train_scaled[:, 0].max():.2f}")

---
## 📝 Practice Exercises

Try these exercises to solidify your learning!

### Exercise 1: NumPy Array Operations

In [ ]:
# TODO: Create a 5x5 matrix with random values between 0 and 100
# Find: mean, median, standard deviation
# Extract all values greater than 50
# Normalize the matrix (subtract mean, divide by std)

# Your code here:

### Exercise 2: Pandas Data Manipulation

In [ ]:
# TODO: Create a DataFrame with columns: Name, Age, City, Salary
# Add 5 rows of data
# Filter people older than 30
# Calculate average salary by city
# Add a new column: Salary_Category (Low, Medium, High based on salary)

# Your code here:

### Exercise 3: Data Visualization

In [ ]:
# TODO: Create a dataset with 100 samples
# Plot: histogram, scatter plot, box plot
# Create a 2x2 subplot with different visualizations

# Your code here:

---
## ✅ Phase Completion Checklist

- [ ] Understand Python basics (loops, functions, lists, dicts)
- [ ] Create and manipulate NumPy arrays
- [ ] Perform vectorized operations
- [ ] Load and analyze data with Pandas
- [ ] Handle missing data
- [ ] Create visualizations with Matplotlib
- [ ] Use Seaborn for statistical plots
- [ ] Complete practice exercises
- [ ] Load and explore a real dataset

---
## 🎯 Key Takeaways

1. **NumPy**: Foundation for numerical computing - arrays are faster than lists
2. **Pandas**: Essential for data manipulation - DataFrames are like Excel on steroids
3. **Matplotlib**: Low-level plotting - complete control over visualizations
4. **Seaborn**: High-level plotting - beautiful statistical visualizations
5. **Vectorization**: Always prefer array operations over loops (50x faster!)

---

## 📚 Next Steps

Once you're comfortable with these tools, move to:
👉 **Phase 1: What is Machine Learning**

---

**Remember:** These tools are your foundation. You'll use them in EVERY ML project. Practice until they become second nature!