In [1]:
# ===================================================================
# Complete NumPy Practice Code – Revision with Output (2025)
# Run this file in Jupyter Notebook or Python script for best experience
# ===================================================================

import numpy as np

print("NumPy version:", np.__version__)
print("="*60)

# Random (modern Generator - recommended)
rng = np.random.default_rng(seed=42)
print("rng.random (3,3)             ->", rng.random((3,3)))
print("rng.integers(0,10,(2,4))     ->", rng.integers(0,10,size=(2,4)))
print("rng.normal(0,1,5)            ->", rng.normal(0,1,5))

print("\n" + "="*60)


NumPy version: 2.0.2
rng.random (3,3)             -> [[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]
rng.integers(0,10,(2,4))     -> [[8 4 5 3]
 [1 9 7 6]]
rng.normal(0,1,5)            -> [ 1.12724121  0.46750934 -0.85929246  0.36875078 -0.9588826 ]



In [ ]:

# --------------------- 1. Array Creation ---------------------
print("1. ARRAY CREATION")
a = np.array([1, 2, 3, 4])
print("np.array([1,2,3,4])          ->", a, a.dtype)

b = np.array([[1, 2], [3, 4]], dtype=np.float64)
print("2D float array               ->", b)

print("zeros (3,4)                  ->", np.zeros((3,4)))
print("ones (2,3, int)              ->", np.ones((2,3), dtype=int))
print("full (3,3, 7)                ->", np.full((3,3), 7))
print("eye 4x4                      ->", np.eye(4))
print("arange(0,10,2)               ->", np.arange(0,10,2))
print("linspace(0,1,5)              ->", np.linspace(0,1,5))
print("logspace(0,3,4)              ->", np.logspace(0,3,4))
print("random (3,3) [0,1)          ->", np.random.random((3,3)))
print("randint 0-9 size=5           ->", np.random.randint(0,10,size=5))

[1 2 3]
2D [[1 2 3]
 [4 5 6]]
3D--- [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape of 3D array (2, 2, 3)


In [ ]:

# --------------------- 2. Attributes ---------------------
print("2. ARRAY ATTRIBUTES")
arr = np.arange(24).reshape(2, 3, 4)   # 2 blocks x 3 rows x 4 cols
print("arr.shape   :", arr.shape)
print("arr.ndim    :", arr.ndim)
print("arr.size    :", arr.size)
print("arr.dtype   :", arr.dtype)
print("arr.itemsize:", arr.itemsize, "bytes")
print("arr.nbytes  :", arr.nbytes, "bytes")
print("arr.strides :", arr.strides)   # very useful for understanding memory layout

print("\n" + "="*60)


2. ARRAY ATTRIBUTES
arr.shape   : (2, 3, 4)
arr.ndim    : 3
arr.size    : 24
arr.dtype   : int64
arr.itemsize: 8 bytes
arr.nbytes  : 192 bytes
arr.strides : (96, 32, 8)



In [ ]:

# --------------------- 3. Data Types ---------------------
print("3. DATA TYPES (dtype)")
print(np.array([1,2,3], dtype=np.int8))
print(np.array([1,2,3], dtype=np.uint8))
print(np.array([1.1, 2.2], dtype=np.float32))
print(np.array(["hello","world"], dtype="U5"))   # Unicode max 5 chars
print(np.array([True, False, True]))

# Structured dtype (like a mini database)
dt = np.dtype([('name', 'U10'), ('age', int), ('weight', float)])
people = np.array([('Alice', 25, 55.5), ('Bob', 30, 80.0)], dtype=dt)
print("Structured array:\n", people)
print("Ages only:", people['age'])

print("\n" + "="*60)


In [ ]:

# --------------------- 4. Indexing & Slicing ---------------------
print("4. INDEXING & SLICING")
m = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15]])

print("m[1,2]           ->", m[1,2])       # 6
print("m[1,:]           ->", m[1,:])       # whole row
print("m[:,2]           ->", m[:,2])       # whole column
print("m[1:, ::2]       ->", m[1:, ::2])   # rows 1-end, every 2nd col
print("m[::-1, ::-1]    -> reversed:\n", m[::-1, ::-1])

# Boolean indexing
print("m > 7            ->", m[m > 7])
print("Even numbers     ->", m[m % 2 == 0])

# Fancy indexing
rows = [0, 3, 1]
cols = [0, 2, 3]
print("Fancy indexing   ->", m[rows, cols])

# Assignment with boolean
m[m % 2 == 0] = -1
print("Even -> -1:\n", m)

print("\n" + "="*60)


In [ ]:

# --------------------- 5. Broadcasting ---------------------
print("5. BROADCASTING")
A = np.arange(1,7).reshape(2,3)
print("A =\n", A)

row_vec = np.array([10, 20, 30])
col_vec = np.array([[100],[200]])

print("A + row_vec      ->\n", A + row_vec)
print("A + col_vec      ->\n", A + col_vec)

print("\n" + "="*60)


In [ ]:

# --------------------- 6. Universal Functions (ufuncs) ---------------------
print("6. UFUNCS")
x = np.linspace(0, 2*np.pi, 5)
print("sin(x)   :", np.sin(x))
print("exp(x)   :", np.exp(x))
print("sqrt(x)  :", np.sqrt(x))
print("x ** 2   :", x**2)

print("np.add.reduce([1,2,3,4]) =", np.add.reduce([1,2,3,4]))  # sum
print("np.maximum([1,9,3],[4,2,8]) =", np.maximum([1,9,3],[4,2,8]))

print("\n" + "="*60)

In [ ]:

# --------------------- 7. Aggregations ---------------------
print("7. AGGREGATIONS")
data = np.arange(1,13).reshape(3,4)
print("data =\n", data)

print("sum          :", data.sum())
print("sum axis=0   :", data.sum(axis=0))   # column sums
print("sum axis=1   :", data.sum(axis=1))   # row sums
print("mean         :", data.mean())
print("std          :", data.std())
print("min, argmin  :", data.min(), data.argmin())
print("max, argmax  :", data.max(), data.argmax())
print("cumsum axis=1:\n", data.cumsum(axis=1))
print("median       :", np.median(data))
print("percentile 75:", np.percentile(data, 75))

print("\n" + "="*60)



In [ ]:

# --------------------- 8. Shape Manipulation ---------------------
print("8. SHAPE MANIPULATION")
x = np.arange(12)
print("original :", x)

print("reshape(3,4):\n", x.reshape(3,4))
print("ravel()    :", x.ravel())
print("flatten()  :", x.flatten())   # returns copy
print("x.T (transpose 1D does nothing):", x.T)

y = x.reshape(3,4)
print("view vs copy example:")
view = y[::2, :]          # view
copy = y[[0,2], :]        # fancy indexing -> copy
print("view.base is y :", view.base is y)
print("copy.base is y :", copy.base is y)

# Stacking
a = np.ones((2,3))
b = np.zeros((2,3))
print("vstack(a,b):\n", np.vstack((a,b)))
print("hstack(a,b):\n", np.hstack((a,b)))
print("stack axis=0:\n", np.stack((a,b), axis=0).shape)  # (2,2,3)

# Adding new axis
print("a[:, np.newaxis].shape :", a[:, np.newaxis].shape)   # (2,1,3)

print("\n" + "="*60)


In [ ]:

# --------------------- 9. Linear Algebra ---------------------
print("9. LINEAR ALGEBRA")
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

x = np.linalg.solve(A, b)
print("Solve Ax=b :", x)

print("A @ A inverse ≈ I :", np.allclose(A @ np.linalg.inv(A), np.eye(2)))

eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues :", eigvals)

print("Matrix norm :", np.linalg.norm(A))

print("\n" + "="*60)

In [ ]:

# --------------------- 10. Random Module (new style) ---------------------
print("10. RANDOM (Generator)")
rng = np.random.default_rng(12345)

print("uniform [0,1) 3x3:\n", rng.random((3,3)))
print("integers 0-9 size=10:", rng.integers(0, 10, 10))
print("normal mean=5 std=2 size=5:", rng.normal(5, 2, 5))
print("choice:", rng.choice(['rock','paper','scissors'], size=5))

arr = np.array([10,20,30,40,50])
rng.shuffle(arr)
print("shuffled in-place:", arr)

print("\n" + "="*60)


In [ ]:

# --------------------- 11. Saving / Loading ---------------------
print("11. SAVE / LOAD")
np.save("/tmp/myarray.npy", data)
loaded = np.load("/tmp/myarray.npy")
print("saved & loaded same:", np.array_equal(data, loaded))

np.savetxt("/tmp/data.csv", data, delimiter=",", fmt="%d")
loaded_txt = np.loadtxt("/tmp/data.csv", delimiter=",")
print("csv load same:", np.array_equal(data, loaded_txt.astype(int)))

print("\n" + "="*60)


In [ ]:

# --------------------- 12. Advanced: einsum ---------------------
print("12. EINSUM EXAMPLES")
A = np.arange(1,5).reshape(2,2)
B = np.arange(5,9).reshape(2,2)
print("A =\n", A)
print("B =\n", B)

print("Trace of A          :", np.einsum('ii->', A))
print("Sum all elements    :", np.einsum('ij->', A))
print("Matrix multiply     :", np.einsum('ij,jk->ik', A, B))
print("Element-wise square :", np.einsum('ij,ij->ij', A, A))
print("Outer product       :", np.einsum('i,j->ij', [1,2,3], [4,5]))

print("\n" + "="*60)


In [ ]:

# --------------------- 13. Set Operations & Unique ---------------------
print("13. SET OPERATIONS")
a = np.array([1,2,3,4,4,5])
b = np.array([4,5,6,7])

print("unique(a)          :", np.unique(a))
print("union1d            :", np.union1d(a,b))
print("intersect1d        :", np.intersect1d(a,b))
print("setdiff1d          :", np.setdiff1d(a,b))
print("in1d [1,4,9] in a  :", np.in1d([1,4,9], a))

print("\n" + "="*60)

print("CONGRATULATIONS! You just executed a complete NumPy revision with real outputs.")
print("Practice these snippets daily and you'll master NumPy in no time! 🚀")